<?php use Curbstone\CardOnFile\Block\Customer\NewCard; ?>
<div id="test-div" data-bind="scope:'cardonfile'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
       {
           "#test-div": {
               "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ /** @var NewCard $block */ echo $block->getJsLayout();?>
           }
       }
   </script>
</div>
<script type="text/javascript">
    window.checkoutConfig = <?php echo \Zend_Json::encode($block->getCheckoutConfig()); ?>;
</script>
